# Generated by Django 5.0.7 on 2024-08-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beirutAdmin', '0005_remove_useradmin_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='url',
            field=models.ImageField(max_length=500, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='specialevents',
            name='image',
            field=models.ImageField(max_length=500, upload_to='special-events'),
        ),
    ]
