# Generated by Django 5.0.7 on 2024-08-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beirutAdmin', '0007_beirutvideos'),
    ]

    operations = [
        migrations.AddField(
            model_name='beirutvideos',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
