# Generated by Django 5.0.7 on 2024-09-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beirutAdmin', '0008_beirutvideos_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='location',
        ),
        migrations.AlterField(
            model_name='menus',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
