# Generated by Django 5.0.7 on 2024-09-26 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beirutAdmin', '0009_reservationstatus_remove_reservations_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='status',
            field=models.BooleanField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beirutAdmin.reservationstatus')),
        ),
    ]
