# Generated by Django 5.0.7 on 2024-09-27 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beirutAdmin', '0010_alter_reservations_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beirutAdmin.reservationstatus'),
        ),
    ]
