# Generated by Django 5.0.7 on 2024-09-27 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beirutAdmin', '0011_alter_reservations_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialevents',
            name='event_location',
        ),
    ]
